# Generated by Django 3.2 on 2025-03-20 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eldapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='user',
        ),
    ]
