# Generated by Django 3.2 on 2025-03-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldapp', '0002_remove_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='current_coordinates',
            field=models.JSONField(default={'lat': 0, 'lng': 0}),
        ),
    ]
