# Generated by Django 3.2 on 2025-03-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldapp', '0003_trip_current_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_coordinates',
            field=models.JSONField(default=dict),
        ),
    ]
