# Generated by Django 3.2 on 2025-03-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eldapp', '0004_alter_trip_current_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dropoff_coordinates',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_coordinates',
            field=models.JSONField(default=dict),
        ),
    ]
